### ISSUE TITLE
Switch layout on external keyboard

### ISSUE THREAD

**Issue by KarimullinArthur** [florisboard/florisboard#1972]
**Hello everyone!**

When I connect physical keyboard I can not switch layout(nothing just happens).
In "samsung keyboard" it possible with Alt-Shift.

I use gestures for switch keybaord in touch mode.
(Maybe it usefull information)

Environment information

- Floris Board v0.3.16
- Install Source: F-Droid
- Device: Samsung Galasy A80
- Android: 11
- oneUI 3.1

**Comment by patrickgold** [comment]
This is less a bug and more the fact that FlorisBoard ignores the physical keyboard, as my primary focus is building and improving the soft keyboard experience. I will convert this issue into a feature proposal for physical keyboard support thus.

**Comment by patrickgold** [comment]
As for the physical keyboard, do you know any other physical keyboard shortcuts that should have an effect in a soft keyboard (maybe by taking your Samsung Keyboard as a reference)?

**Comment by KarimullinArthur** [comment]
Samsung keyboard have 3 shortcuts:
- Left Alt + Shift
- Control + Space 
- Shift + Space 

But on PC I use CapsLock for this, and Control + CapsLock for Caps Lock :)

I'm will be glad if FlorisBoard too have this shortcats(CapsLock).

**Comment by patrickgold** [comment]
What exactly does CTRL+SPACE and SHIFT+SPACE do in the Samsung keyboard?

**Comment by KarimullinArthur** [comment]
Switch layout.

And may off/onn some shortcut:
![Screenshot_20220727-032516_Settings_1](https://user-images.githubusercontent.com/51211371/181123280-bd757f7a-6fe4-4f7f-b83c-84597e474954.png)

Ahh stop, maybe it system settings, no samsung keyboard, and samsung keyboard just support they -_-

**Comment by KarimullinArthur** [comment]
By the way, Ctrl + A, Ctrl + C, select via Shift + arrows and another shortcuts is work, not work only switch layout.

**Comment by KarimullinArthur** [comment]
@patrickgold ?

**Comment by koiuo** [comment]
@patrickgold , 

I believe every keyboard has to implement its own shortcut for switching input layouts. For example, Google's GBoard allows switching by Ctrl + Space, and completely ignores the dedicated setting on Samsung tablets. Samsung's OneUI provides tight integration with its own soft keyboard. Also on Samsung keyboard folios there's a dedicated language switch key and I'm sure Samsung's soft keyboard listens to its scancode and reacts appropriately.
While integration with Samsung OneUI definitely would be nice (as it's probably the most popular tablet vendor on Android), I don't think this should be a priority.

IMHO, the first priority for florisboard in the scope of physical keyboard support — is listening to some scan/key code combination (ctrl+space, following GBoard's choice, for example) and cycling through configured input layouts.

**Comment by gisturbance** [comment]
@patrickgold 
> This is less a bug and more the fact that FlorisBoard ignores the physical keyboard, as my primary focus is building and improving the soft keyboard experience. I will convert this issue into a feature proposal for physical keyboard support thus.

It would be very useful to show a keyboard switcher (as gboard does), as well as an option to show the on-screen keyboard while a phyiscal keyboard is connected.

**Comment by lm41** [comment]
Potentially fixed with #2981

**Comment by ghost** [comment]
Still missing these key functional feature for physical keyboard support:

- IME.
- IME switcher.
