### ISSUE TITLE
Only allow max. one gesture in a row

### ISSUE THREAD

**Issue by Glitchy-Tozier** [florisboard/florisboard#487]
- If you swipe on your keyboard and accidentally touch your spacebar/delete icon, the spacebar/delete gesture will be initiated.
- If you spacebar-swipe to move your cursor across the text, and you move your finger a little too high up, you'll trigger the up-motion of your keyboard.
- If you open a pop-up by long-pressing a key, then cancel the popup by swiping away, if your swiping-motion hits spacebar/delete, their gestures will be triggered.
- You can create neat combinations of those effects. For example, combo bullet point 3 with nr. 2 for a maximum of chaos that ends with switching active keyboards (up gesture) 🤣

In my opinion, those behaviours are a bit weird. I suggest this:
- If a gesture on any part of the keyboard is performed, deactivate all other gesture-containing areas until the finger is removed from the screen
- After opening a pop-up character selection, disable all pop-ups until the finger is lifted off of the screen.

**Comment by patrickgold** [comment]
Thanks for your suggestion! That's true, you can currently trigger more than one gesture at once. May be a bit tricky to fix this, as there are different swipe detection contexts which all work together, but I am sure I'll find a way. Will add it to the todo list!

**Comment by Glitchy-Tozier** [comment]
As a lazy programmer, I'd just add some global variable that, if True, disables all other gestures.

Depeniding on how Florisboard works that might not be possible though. Also, I have no idea what is considered to be "clean" progamming.

**Comment by patrickgold** [comment]
> As a lazy programmer, I'd just add some global variable that, if True, disables all other gestures.

I mean that would definitely work, haha

> Also, I have no idea what is considered to be "clean" progamming.

Global variables should be avoided when possible, but adding a service-wide variable for this is the cleaner way.

**Comment by Glitchy-Tozier** [comment]
Tell me what you decided when you tackle this issue!  :)

**Comment by Glitchy-Tozier** [comment]
@patrickgold Could it be that this has been fixed already?
I can't quite replicate it, but i might be missing small effects that only you know about.

**Comment by patrickgold** [comment]
Ok I just tried the different issues from the initial list and these are my results:

> If you swipe on your keyboard and accidentally touch your spacebar/delete icon, the spacebar/delete gesture will be initiated.

Fixed.

> If you spacebar-swipe to move your cursor across the text, and you move your finger a little too high up, you'll trigger the up-motion of your keyboard.

Not fixed, but you have to move your finger abruptly upwards and immediately release afterwards to trigger it, so at least not that annoying anymore.

> If you open a pop-up by long-pressing a key, then cancel the popup by swiping away, if your swiping-motion hits spacebar/delete, their gestures will be triggered.

Fixed.

> If a gesture on any part of the keyboard is performed, deactivate all other gesture-containing areas until the finger is removed from the screen

Absolutely not fixed (use space and delete and see the cursor panicking xd)

> After opening a pop-up character selection, disable all pop-ups until the finger is lifted off of the screen.

Fixed (a new finger automatically cancels other popups)

**Comment by Glitchy-Tozier** [comment]
> Absolutely not fixed (use space and delete and see the cursor panicking xd)

Oh, yeah!  xD
Well, let's leave the issue open, then!
